global:
  smtp_smarthost: <SMTPHOST>
  smtp_from: abc@def.com
  smtp_require_tls: false
route:
  group_wait: 30s
  group_interval: 5m
  group_by: ['instance']
  repeat_interval: 1h
  receiver: team-X-mails
  routes:
  - match:
      alertname: 'Host Monitor'
    receiver: host_down-receiver
  - match:
      alertname: 'Disk_Space_Windows_Live'
    receiver: Disk-Space-receiver
  - match:
      alertname: 'Disk_Space_Linux_Live'
    receiver: Disk-Space-receiver
receivers:
- name: 'host_down-receiver'
  email_configs:
  - to: 'abc@def.com'
    headers:
      subject: "VM(s) Down"
- name: 'Disk-Space-receiver'
  email_configs:
  - to: 'abc@def.com'
    headers:
      subject: "Disk Space issue"
- name: 'team-X-mails'
  email_configs:
  - to: 'abc@def.com'
    headers:
      subject: "You have {{ .Alerts.Firing | len }} alert(s)"
