global:
  smtp_smarthost: <SMTP_HOST>
  smtp_from: <abc@def.com>
  smtp_require_tls: false
route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h 
  receiver: team-X-mails
receivers:
- name: 'team-X-mails'
  email_configs:
  - to: '<abc@def.com>'
    headers:
      subject: "You have {{ .Alerts.Firing | len }} alert(s)"
